# Site settings
theme: jekyll-theme-minima
title: あの忘れえぬ日々 そのために今生きている
email: kimitoboku@techack.net
url: "http://blog.techack.net"
encoding: utf-8
author :
  name : Kawakami Kento
  email : emaxser@bonprosoft.com
github: kimiboku
google_analytics: UA-21221719-2


# Build settings
markdown: kramdown
permalink: /archive/:year/:month/:day/:title
