# Site settings
theme: minima
title: あの忘れえぬ日々 そのために今生きている
url: "http://blog.techack.net"
encoding: utf-8
author :
  name : Kento KAWAKAMi
  email: kimitoboku@techack.net
github: kimiboku
google_analytics: UA-21221719-2


# Build settings
markdown: kramdown
permalink: /archive/:year/:month/:day/:title
