# Site settings
theme: hacker
title: あの忘れえぬ日々 そのために今生きている
email: emxaser@bonprosoft.com
url: "http://blog.techack.net"
encoding: utf-8
author :
  name : Kawakami Kento
  email : emaxser@bonprosoft.com
github: kimiboku
google_analytics: UA-21221719-2


# Build settings
markdown: kramdown
permalink: /archive/:year/:month/:day/:title
